name: pedantic_mono
description: '[mono edition] Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.'
version: 1.34.0
repository: https://github.com/mono0926/pedantic_mono
funding:
  - https://github.com/sponsors/mono0926

environment:
  sdk: ^3.9.0

dependencies:
  flutter_lints: ^6.0.0

dev_dependencies:
  grinder:
  http:
  yaml:
topics:
  - lint
  - lints
  - linter
  - analysis
  - code-style
